### PR TITLE
Fix for #247

### PR DESCRIPTION
**Pull request by moulins**
This should allow Amidst to work with minecraft 1.11.

I'm not 100% sure that the fingerprints for the 2 new minecraft classes needed are future-proof, but for now it works!

I've also taken this opportunity to simplify the workings of the class translator by removing the ```RCDBuilder``` and ```***RCD``` classes (which are useless now that we have lambda-expressions).

### CODE REVIEW

**Comment by mathuin** [comment]
While multiple anecdotes are not data, I can tell you that I was able to successfully build the JAR file from this pull request and run it with a 1.11 profile, and I'm seeing what I expect to see.

**Comment by the-ntf** [comment]
It took me several hours to to get the build process right, but I was ultimately able to aply this fix and can attest that it also works for me in 1.11

**Comment by stefandollase** [comment]
Thanks for finding the necessary classes and methods and for fixing the issue!

I am not yet sure whether I like that you replaced a part of the detection language my lambda expressions, but I guess it works :-P

**Comment by Fear837** [comment]
Is there a version planned where you can find the new Woodland Mansions?

**Comment by stefandollase** [comment]
@Fear837
See #233. We plan to support it at some unknown point in the future.

**Pull request merged**
