### PR TITLE
Update JDK version from 1.8 to 1.16

### PR DESCRIPTION
**Pull request by Mobmaker55**
This is the fix required to make the executable work. 
I couldn't figure out how to use Travis-CI because I'm not the most intelligent person ever, so I can't compile it for everyone else, but here's the fix for the 40 some issues that have been created for 1.17.

### CODE REVIEW

**Comment by thegreatgoose** [comment]
Anyone with the knowledge to compile this? Seems like the developer of the project isn't very active. :(

**Comment by Mobmaker55** [comment]
> 
> 
> Anyone with the knowledge to compile this? Seems like the developer of the project isn't very active. :(

Yeah, I'll just compile it on my branch I guess 🤷‍♂️ 

Give me like 30m to make a release

**Comment by FakenameBill** [comment]
Are the devs still active? This seems like such an easy issue to fix.

**Comment by mpsijm** [comment]
@thegreatgoose See #1088, I pushed the binaries at https://github.com/mpsijm/amidst/releases/tag/v4.7-java-17 :slightly_smiling_face:

**Pull request closed without merging**
