### PR TITLE
Stub for the export functionality of AmidstExporter

### PR DESCRIPTION
**Pull request by stefandollase**
@Treer I added a stub for the export functionality, so you do not have to figure out yourself how to integrate it into the GUI. You should be able to write to this pull request to implement the actual export function.

### CODE REVIEW

**Comment by stefandollase** [comment]
I enhanced the stub, see the commit message for more details. I also added a "TODO: implement me!" where you need to add the implementation.

**Comment by stefandollase** [comment]
@Treer Did you already start commiting to this branch? I do not want to pressure you. Take all the time you want. The only reason I am asking is, that if you did not yet commit to this branch, I would go ahead and resolve the merge conflicts by merging in the current master. So, it will be easier to merge this branch into master later on.

**Comment by Treer** [comment]
Cheers, I haven't started working on it. I've merged in the changes, and will so again if it's needed before I start working on it.

**Comment by stefandollase** [comment]
Good, that you already did it. I was unsure about how comfortable you would be with doing so.

Also good to know your plans for AmidstExporter :-)

**Comment by Treer** [comment]
I did need the hint

**Comment by stefandollase** [comment]
@Treer
How is your current state about porting the export functionality? I don't mean to harass you, but I noticed that I can reuse some code from this branch to better integrate #120 into Amidst.

Do you have unpushed commits based on this branch? If not, I will add a [feature toggle](http://martinfowler.com/bliki/FeatureToggle.html) for the menu entry and merge it back into the master. The feature toggle hides the unfinished functionality from the user, but it allows the parallel development of features that can share some code. This will also prevent this branch from causing a big merge conflict when it is integrated.

Of course, this would mean that you would have to create a new pull request to actually implement the export functionality, but this should not be an issue.

**Comment by Treer** [comment]
I haven't started on it :) Add away.

I'll probably finish beta oceans before doing exporting.

**Comment by stefandollase** [comment]
Thanks for the feedback. I will merge it this week.

**Comment by burgerguy** [comment]
This stub ended up getting used for #716, but if AmidstExporter were to ever return then we could add it back.

**Pull request merged**
