### PR TITLE
Working filtered random seed demo

### PR DESCRIPTION
**Pull request by mgod**
Addresses #120.

Working search configured by a search.json file in the home directory. Feature work:

- [x] Basic filter structure
- [x] Run filter correctly in ```Actions```
- [x] Build JSON interface to specify parameters for
  - [x] biome filters
  - [x] structure filters
  - [x] continuous search with logging
- [ ] finish documentation

### CODE REVIEW

**Comment by stefandollase** [comment]
This was quick. I like the package location in `amidst.mojangapi.world.filter`.

However, I do not like the formatting. We don't have a Checkstyle or something similar, however we decided to use the Eclipse formatter, which gives at least kind of a common structure. Sadly, the Eclipse formatter seemed to have changed between version, so it is not that common as I would like it to be. However, for now it is good enough. In Eclipse, you can apply the formatter to complete source folders via the context menu in the Package Explorer.

Next, I don't like how you hook into the current code. The Actions class is there to contain only the minimal amount of code which is necessary to translate a GUI command to method calls on the object graph. Thus, there should probably be a new menu entry to search for a seed. This would create a new WorldFinder, which creates new worlds with a random seed and checks whether the seed matches the requirements. This should be independent of the displayed world, which means a WorldFinder will need a new instance of the MojangApi, but especially a new instance of the MinecraftInterface. Thus, the WorldFinder currently is pretty much your code in the method `newFromRandom`.

You need to duplicate the MojangApi, because you cannot reuse the MinecraftInterface for different World objects. As soon as you create a new World, all calls to the old World will result in undefined behaviour. However, you would have two World objects running with one MinecraftInterface as soon as you create the new Worlds in the background with the same MinecraftInterface, independent from the displayed World.

If you did not understand something, please let me know.

**Comment by mgod** [comment]
Ah, I was wondering why the UI started loading strange data while the search was running. Thanks for the feedback! I'll try to address these points soon.

**Comment by mgod** [comment]
Hopefully the formatting is now more correct.

I moved things out of the Actions class as much as made sense. I feel like I may be missing a better way to handle updating the main window with seeds as creating classes on the fly always feels messy.

I'm also using a separate copy of the API now so the UI doesn't have weird behavior while searching anymore. Please let me know if my code to duplicate the API looks bad to you, but it seems to work correctly.

I'll be changing how to WorldFinder gets created so we can pass in a configuration in to it next. I'll post a proposed configuration file before I code it.

**Comment by mgod** [comment]
I think this syntax will be reasonably easy to implement and give a reasonable range of flexibility for end users:

```
{
  "continuousSearch": false
  "biomeFilters": [
    {"distance": 1024, "biomes": ["Mesa (Bryce)", "Mesa Plateau F M", "Mesa Plateau M"] },
    {"distance": 4096, "biomes": ["Mushroom Island", "Mushroom Island M"]}
  ],
  "structureFilters": [
    {"distance": 1024, "structure": "Village", "minimum": 1}
  ]
}
```

If continuous search is set to true, the world finder just keeps finding new seeds and setting them in the main window. The intent would be to run this for a while with the history logger, then review the seeds it found. Defaults to false.

The biome filters would match if ANY of the list of biomes are present within the distance from 0,0. The names of the biomes must match the listing in amidst.mojangapi.world.biome.Biome.java.

The structure filters match if there are at least minimum count of that structure within the distance from 0,0. The names of the structures would need to match DefaultWorldIconTypes, which I'm not sure is OK because that file enum has some warnings about using it as a type.

**Comment by mgod** [comment]
Ok, the search is configurable now and I've cleaned up some of the integration points. I'm happy to look at making the code in Actions.java even less intrusive if it still feels off to you. I think I've got my formatter configured correctly for this project now as well, so this should be closer to the existing style.

This is probably ok to merge with the exception that I want to have the alert about search not being configured include a url to some documentation in the wiki. I'd like to create a wiki page with the following content, so let me know if this would be ok:

### Search configuration file

You should add a file called search.json next to the Amidst jar file. Here's an sample configuration:

```
{
  "continuousSearch": false,
  "biomeFilters": [
    {"distance": 1024, "biomes": ["Mesa (Bryce)", "Mesa Plateau F M", "Mesa Plateau M"] },
    {"distance": 4096, "biomes": ["Mushroom Island", "Mushroom Island M"]}
  ],
  "structureFilters": [
    {"distance": 1024, "structure": "Village", "minimum": 1}
  ]
}
```

If continuous search is set to true, the search keeps finding new seeds and setting them in the main window. You should run this with the history logger, then review the seeds it found. Defaults to false.

The biome filters match if ANY of the list of biomes are present within the distance from 0,0. The names of the biomes must match the listing in amidst.mojangapi.world.biome.Biome.java.

The structure filters match if there are at least minimum count of that structure within the distance from 0,0.

All distances must be a multiple of 512.

### Supported structure names

 - Stronghold
 - Jungle Temple
 - Desert Temple
 - Igloo
 - Witch Hut
 - Village
 - Ocean Monument
 - Mineshaft

Search currently does not support End or Nether structures.

### Biome names for version 1.9

 - Ocean
 - Plains
 - Desert
 - Extreme Hills
 - Forest
 - Taiga
 - Swampland
 - River
 - Hell
 - The End
 - Frozen Ocean
 - Frozen River
 - Ice Plains
 - Ice Mountains
 - Mushroom Island
 - Mushroom Island Shore
 - Beach
 - Desert Hills
 - Forest Hills
 - Taiga Hills
 - Extreme Hills Edge
 - Jungle
 - Jungle Hills
 - Jungle Edge
 - Deep Ocean
 - Stone Beach
 - Cold Beach
 - Birch Forest
 - Birch Forest Hills
 - Roofed Forest
 - Cold Taiga
 - Cold Taiga Hills
 - Mega Taiga
 - Mega Taiga Hills
 - Extreme Hills+
 - Savanna
 - Savanna Plateau
 - Mesa
 - Mesa Plateau F
 - Mesa Plateau
 - Ocean M
 - Sunflower Plains
 - Desert M
 - Extreme Hills M
 - Flower Forest
 - Taiga M
 - Swampland M
 - River M
 - Hell M
 - Sky M
 - Frozen Ocean M
 - Frozen River M
 - Ice Plains Spikes
 - Ice Mountains M
 - Mushroom Island M
 - Mushroom Island Shore M
 - Beach M
 - Desert Hills M
 - Forest Hills M
 - Taiga Hills M
 - Extreme Hills Edge M
 - Jungle M
 - Jungle Hills M
 - Jungle Edge M
 - Deep Ocean M
 - Stone Beach M
 - Cold Beach M
 - Birch Forest M
 - Birch Forest Hills M
 - Roofed Forest M
 - Cold Taiga M
 - Cold Taiga Hills M
 - Mega Spruce Taiga
 - Mega Spruce Taiga (Hills)
 - Extreme Hills+ M
 - Savanna M
 - Savanna Plateau M
 - Mesa (Bryce)
 - Mesa Plateau F M
 - Mesa Plateau M

**Comment by BlueSteelAUS** [comment]
how can i pull these changes to my https://github.com/BlueSteelAUS/amidst.git and make another branch from it and them merge it with my changes in yet another tree..

still fairly new to git. and don't know how to do everything

**Comment by mgod** [comment]
@BlueSteelAUS I'm not sure what the best approach is for you, but you'll probably either want to check this out in a separate branch in your local repository and then merge it into your main branch or rebase your main branch off of this.

**Comment by mgod** [comment]
@stefandollase I've been playing with this filter for a while, and I think it needs two additions, though it does work fine as is.

I think I should add some UI component showing status of the search (if your filters are fairly restrictive, it can just feel like the program is doing nothing) and also add something that allows you to specify a % match that is acceptable that gets displayed somewhere (search seeds that match 80% of the filters, for example).

These aren't strictly necessary and I don't want to add more complexity than is reasonably reviewable. Do you think I should add these now or wait until you've decided if these can be merged first, the open an improvement PR?

**Comment by stefandollase** [comment]
@BlueSteelAUS If you just want to look at the changes, I recommend doing this on Github. You can do this [here](https://github.com/toolbox4minecraft/amidst/pull/123/files) or directly in [the fork of mgod](https://github.com/mgod/amidst). If you want to view the changes locally on your machine, you can clone the fork of mgod, separately to your machine. Please, only work with multiple branches in your own repository if you really want to work with them and you know what you are doing.

@mgod Thanks for all your work. I hope I soon get the time to review the changes, but I think that I won't be able to do this until the end of this month. From what you wrote here, it looks great! I also agree with you, that there should not be more complexity added until I reviewed the changes.

One minor thing that I just noticed is, that you did not create a separate branch for your changes, but you committed directly to your master. If you know how to do this: Can you please move your changes to a new branch and create a new pull request from the new branch?

**Comment by mgod** [comment]
Moved PR to #129 to move the feature off of my master branch.

**Pull request closed without merging**
