### PR TITLE
proposed updates to nether fortress and stronghold icons and slimechunk colour 

### PR DESCRIPTION
**Pull request by BlueSteelAUS**
proposed updates to nether fortress and stronghold icons and slime chunk colour as under discussion in issues

### CODE REVIEW

**Comment by stefandollase** [comment]
This is related to #114 and #107.

Please have a look at the wiki section [Writing Code](https://github.com/toolbox4minecraft/amidst/wiki/Supporting-the-Development#writing-code). Especially, changes should be made in a new branch, but not in master. Please have a look at the Github Flow, which is linked from there.

It is fine to add the `.metadata` directory to `.gitignore`. However, you really should not have it in the project directory. The project directory should be a subfolder in you workspace directory. It can even be placed at a totally different location.

I am still not sure about the new Nether Fortress icon, but more about this in #107.

**Comment by BlueSteelAUS** [comment]
sorry i'm a newbee when it comes to git. all self learned. any tips / lessons would be appreciated. which is the main reason i'm doing the changes in my own fork. i don't want to stuff things up in the main repo.

in my prevous project i used master as the dev and releases as branches

**Comment by BlueSteelAUS** [comment]
to update with new netherfortress proposal do i close this pull request and open another ?

**Comment by stefandollase** [comment]
I just changed the slime chunk color by myself, to be able to include it in the v4.1 release. Can you create another pull-request once we agreed on the new icons? I will close this one.

Please create a new branch for the new pull request in you forked repository. After you push this new branch to your fork, Github will suggest you to create a pull-request from the new branch. You might also want to read about feature branches as well as the [Github Flow](https://guides.github.com/introduction/flow/).

**Pull request closed without merging**
