### PR TITLE
Cache Fragments when off-screen

### PR DESCRIPTION
**Pull request by magicus**
This PR implements caching of Fragments, as requested and discussed in #451. 

The SoftRef implementation guarantees that the GC will free elements in the cache before running out of memory. The cache will be invalidated whenever the complete set of fragments is to be recycled, i.e. when we're switching seed, etc. Loading of new fragments will proceed exactly as before, unless the fragment is found in the cache, in which case it will be reused. A fragment that was requested to be loaded at some point (e.g. by the user scrolling to that part), but then was retired (by that part going off the screen again) will still be eligible for loading, but in the background, when all visible fragments has been loaded. That way, if a user scrolls this way and that, chances are the fragment is loaded and cached when she returns to that part of the map.

### CODE REVIEW

**Comment by burgerguy** [comment]
Amidst not doing this currently is kind of a large problem. If you want to zoom in on an area for a short amount of time, when you zoom out, you have to wait for it to regenerate all of the fragments again.

**Comment by magicus** [comment]
@moulins Is there anything holding back this PR being merged? If you need any specific changes, please let me know. I'll be happy to update it to fit with the projects style guide, as well as long-term vision.

**Comment by moulins** [comment]
Sorry, I didn't have time to test the PR myself.

-----

I did have time to run some tests today, and while moving the map around for a few minutes, RAM usage kept increasing. It seems that the background fragments never get garbage-collected, and when I stopped moving around the fragment cache has grown to more than 10k entries.

I see two potential causes for this:
- when a fragment is retired, it is added to the background queue, which means it can't be reclaimed by the GC until it is fully loaded by the fragment loader;
- in the `FragmentManager`, there is both `FragmentCache cache` and `Map<CoordinatesInWorld, SoftReference<Fragment>> fragmentCache`. I'm not entirely sure this is a problem, but I think it would be clearer if the `Map` was inside the `FragmentCache` instead.

In addition, it would be nice (and help with debugging) if the status of the background queue was displayed by the `DebugWidget` alongside the other queues.

**Comment by burgerguy** [comment]
I've been recently working on a branch ([here](https://github.com/burgerguy/amidst-changes/tree/multithreaded-fragment-cache)) which rewrites most of the fragment queues and caches fragments. In short, the normal `FragmentCache` was removed, as well as the `availableQueue`. Now, there are separate classes `OffScreenFragmentCache` and `AvailableFragmentCache`. The off-screen fragments have a limited lifespan of 30 seconds so they don't take up too much ram, and they are also `SoftReference`s so they don't cause an OOME. The `AvailableFragmentCache` is in place of the old `availableQueue` and adds some extra features. It uses `SoftReference`s, but they don't have an expiration time. A thread gets spawned to clean and maintain both of these caches every half a second.

With the `FragmentCache` being gone, this means that no cache will have the on-screen fragments once they are all done loading. We now have to get them from the `FragmentGraph` instead, and it's used for when we need to invalidate a layer and put the fragments back in the `loadingQueue`.

Overall, it should make the fragment pipeline a bit simpler and should also use a lot less ram.

**Comment by magicus** [comment]
Nevermind this PR then...

I've frankly given up on Amidtst myself anyway; the chunkbase javascript app is way faster. (I think this state of affairs is a bit sad, though.)

**Pull request closed without merging**
